Modify CertificateOptionsMapper logic  when company status is dissolved
companieshouse/order-notification-sender pull request #23
Opened 2022-07-01 11:37 UTC by kinpang-CH

* Add new conditional check to disable doMapCustomData when status is dissolved
* Add new companyStatus field to CertificateOrderNotificationModel
* Test locally for different company types and statuses, email all still works as intended.

Resolves [BI-9946](https://companieshouse.atlassian.net/browse/BI-9946)

2022-07-01 11:49 UTC, sthompsonCH approved these changes

2022-07-01 15:05 UTC, dlgroves-ch requested changes
See https://github.com/companieshouse/chs-notification-api/pull/351#pullrequestreview-1026338865.

2022-07-01 15:05 UTC, dlgroves-ch commented on src/main/java/uk/gov/companieshouse/ordernotification/emailsendmodel/CertificateOptionsMapper.java
> +    private final String COMPANY_STATUS_DISSOLVED = "dissolved";
This constant needs a `static` modifier.

2022-07-06 10:19 UTC, sthompsonCH approved these changes

2022-07-06 12:30 UTC, dlgroves-ch approved these changes

2022-07-06 13:00 UTC, amartin7663 approved these changes

2022-07-06 13:05 UTC, merged