BI-8401 Map fields to readable values
companieshouse/order-notification-sender pull request #5
Opened 2021-08-04 11:40 UTC by dlgroves-ch

* Map certificate type field to a readable value.
* Map delivery type and timeframe to a readable value.
* Map appointment details to readable values.
* Map registered office address to a readable value.
* Add Jacoco plugin to project POM file.

2021-08-04 13:05 UTC, cgregoryCH requested changes

2021-08-04 13:05 UTC, cgregoryCH commented on src/main/java/uk/gov/companieshouse/ordernotification/emailsendmodel/CertificateTypeMapper.java
> +}
Remove component and qualifier annotations. Add java docs

2021-08-04 13:05 UTC, cgregoryCH commented on src/main/java/uk/gov/companieshouse/ordernotification/emailsendmodel/AddressRecordTypeMapper.java
> +}
Remove component and qualifier annotations. Add java docs

2021-08-04 13:05 UTC, cgregoryCH commented on src/main/java/uk/gov/companieshouse/ordernotification/emailsendmodel/DeliveryMethodMapper.java
> +}
Remove component and qualifier annotations. Add java docs

2021-08-04 13:50 UTC, cgregoryCH approved these changes

2021-08-05 11:22 UTC, kinpang-CH approved these changes

2021-08-05 11:22 UTC, cgregoryCH approved these changes

2021-08-05 11:25 UTC, merged